"""Add Dev-Company many-to-many relationship

Revision ID: 4da5bd63bf9d
Revises: a7479f08fe51
Create Date: 2025-05-25 11:38:44.137386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da5bd63bf9d'
down_revision = 'a7479f08fe51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
