"""Add Dev-Company many-to-many relationship

Revision ID: a9edfab9aa8d
Revises: 4da5bd63bf9d
Create Date: 2025-05-25 11:44:23.634631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9edfab9aa8d'
down_revision = '4da5bd63bf9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
